# Generated by Django 4.2 on 2023-09-03 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menuitemCategory',
            field=models.CharField(choices=[('APET', 'Appetizer'), ('MAIN', 'Main Course'), ('DSRT', 'Dessert'), ('SIDE', 'Side'), ('DRNK', 'Drink')], default='DRNK', max_length=4),
        ),
        migrations.CreateModel(
            name='RecipeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0, verbose_name='Price')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient', verbose_name='Ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem', verbose_name='Menu Item')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True, verbose_name='Timestamp')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.menuitem', verbose_name='Menu item')),
            ],
        ),
    ]
